'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class FutureIQDataAdmin1

    '''<summary>
    '''Label1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtNewEffectiveDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNewEffectiveDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblComponentId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblComponentId As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtNewComponentId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNewComponentId As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblComponentType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblComponentType As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlNewComponentType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlNewComponentType As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblComponentDemand control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblComponentDemand As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtNewDemand control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNewDemand As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblMinInventory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMinInventory As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtNewMinInventory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNewMinInventory As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblMaxInventory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMaxInventory As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtNewMaxInventory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNewMaxInventory As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblMachine control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMachine As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtMachine control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMachine As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblPackaging control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPackaging As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlComponentPackaging control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlComponentPackaging As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnAddNewRecord control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddNewRecord As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblTest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTest As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlComponentTypes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlComponentTypes As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''gvFutureIQInputs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvFutureIQInputs As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''dsFutureInputs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsFutureInputs As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''lblSql control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSql As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''dsComponentTypes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsComponentTypes As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''dsPackaging control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsPackaging As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''dsComponentPackaging control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsComponentPackaging As Global.System.Web.UI.WebControls.SqlDataSource
End Class
